
package com.student.attendance;

import javax.swing.*;

/**
 *
 * @author abc
 */
public class LoginPanel extends javax.swing.JPanel {

    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jpf = new javax.swing.JPasswordField();
        jbl = new javax.swing.JButton();
        jl = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(370, 290));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Login Form");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 150, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("UserName");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 100, 30));

        jtf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        add(jtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 100, 30));

        jpf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        add(jpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, 30));

        jbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbl.setForeground(new java.awt.Color(0, 153, 153));
        jbl.setText("LogIn");
        jbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblActionPerformed(evt);
            }
        });
        add(jbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 85, 30));

        jl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(jl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 200, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblActionPerformed
        
         String username=jtf.getText();
        String password =jpf.getText();
        boolean b = lb.checkAvailability(username, password);
         if(b){
            jl.setText("Login Successfull");
        MainFrame m=new MainFrame();
        m.setVisible(true);
        }
        else{
            jl.setText("Login Invalid");
        }
    }//GEN-LAST:event_jblActionPerformed

    public static void main(String[] args) {
        JFrame fr = new JFrame("Login Page");
        fr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fr.setContentPane(new LoginPanel());
        fr.setBounds(500, 100, 500,375);
        fr.setVisible(true);
    }
    LoginBean lb = new LoginBean();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbl;
    private javax.swing.JLabel jl;
    private javax.swing.JPasswordField jpf;
    private javax.swing.JTextField jtf;
    // End of variables declaration//GEN-END:variables
}
