/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.student.attendance;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abc
 */
public class SearchPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchPanel
     */
    public SearchPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSearchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Search Student");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 11, 194, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Enter Name or Enrollment No.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 60, 250, 30));

        jSearchField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchFieldActionPerformed(evt);
            }
        });
        add(jSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 200, 30));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1250, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchFieldActionPerformed
        Vector rows = s.getRecords(jSearchField.getText());
        Vector columns = s.getColumns();
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        dm.setDataVector(rows, columns);
 // TODO add your handling code here:
    }//GEN-LAST:event_jSearchFieldActionPerformed

StudentBean s=new StudentBean();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSearchField;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
