/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.student.attendance;

import javax.swing.JFrame;

/**
 *
 * @author abc
 */
public class StudentInfoPanel extends javax.swing.JPanel {
static double ttotal=0,tattended=0,tpercentage=0,ptotal=0,pattended=0,ppercentage=0,aspecial=0,afinal=0;
   
    /**
     * Creates new form StudentInfoPanel
     */
    public StudentInfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFirstN = new javax.swing.JTextField();
        jFatherN = new javax.swing.JTextField();
        jMob = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCBranch = new javax.swing.JComboBox<>();
        jLastN = new javax.swing.JTextField();
        jId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAdd = new javax.swing.JTextArea();
        jBAdd = new javax.swing.JButton();
        jEnroll = new javax.swing.JTextField();
        jCSem = new javax.swing.JComboBox<>();
        jRefresh = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Student Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 265, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Enrollment No.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("First Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 100, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Father Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 100, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Mobile No.");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 100, 30));

        jFirstN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(jFirstN, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 150, 200, 30));

        jFatherN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(jFatherN, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 200, 200, 30));

        jMob.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(jMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 250, 200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Branch");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 100, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Last Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 150, 100, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Semester");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 200, 100, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Email-ID");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 250, 100, 30));

        jCBranch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "CSE", "EC", "ME", "EX", "CE", "EE", "IP" }));
        add(jCBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, 65, 30));

        jLastN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(jLastN, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 150, 200, 30));

        jId.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(jId, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 250, 200, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Address");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 100, 30));

        jAdd.setColumns(20);
        jAdd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jAdd.setRows(5);
        jScrollPane1.setViewportView(jAdd);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 220, 60));

        jBAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBAdd.setForeground(new java.awt.Color(0, 153, 153));
        jBAdd.setText("Add");
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });
        add(jBAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, 35));

        jEnroll.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(jEnroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 100, 200, 30));

        jCSem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCSem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        add(jCSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, 50, 30));

        jRefresh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRefresh.setForeground(new java.awt.Color(0, 153, 153));
        jRefresh.setText("Refresh");
        jRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRefreshActionPerformed(evt);
            }
        });
        add(jRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, -1, 35));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 310, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed
         s.setsenrollno(jEnroll.getText());
        s.setSfirstname(jFirstN.getText());
        s.setSlastname(jLastN.getText());
        s.setSfname(jFatherN.getText());
        s.setSbranch(jCBranch.getSelectedItem().toString());
        s.setSsem(Integer.parseInt(jCSem.getSelectedItem().toString()));
        s.setSmobile(jMob.getText());
        s.setSemail(jId.getText());
        s.setSaddress(jAdd.getText());

        ab.setSenrollno(jEnroll.getText());
        ab.setAttotal((int) ttotal);
        ab.setAtattended((int) tattended);
        ab.setAtpercentage(tpercentage);
        ab.setAptotal((int) ptotal);
        ab.setApattended((int) pattended);
        ab.setAppercentage(ppercentage);
        ab.setAspecial((int) aspecial);
        ab.setAfinal(afinal);


boolean b0=s.checkAvailablity(jEnroll.getText());
if(b0){
            jLabel11.setText("Student Allready Registered!");
}
 else{
        boolean b=s.add();
        boolean b1=ab.add();
        if(b){

            if(b1){
            jLabel11.setText("Data Recorded Successfully");


            }


        }
 else{
            jLabel11.setText("Please Datafill Correctively");
 }

        }

    }//GEN-LAST:event_jBAddActionPerformed

    private void jRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRefreshActionPerformed
         jEnroll.setText("");
        jFirstN.setText("");
        jLastN.setText("");
        jFatherN.setText("");
        jMob.setText("");
        jId.setText("");
        jAdd.setText("");
jLabel11.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_jRefreshActionPerformed

    
       public static void main(String[] args) {
        JFrame fr = new JFrame("Student Information");
        fr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fr.setContentPane(new StudentInfoPanel());
        fr.setBounds(20, 10, 1300,600);
        fr.setVisible(true);
    }
       
  StudentBean s=new StudentBean();
AttendanceBean1 ab=new AttendanceBean1();
LoginBean lb=new LoginBean();


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jAdd;
    private javax.swing.JButton jBAdd;
    private javax.swing.JComboBox<String> jCBranch;
    private javax.swing.JComboBox<String> jCSem;
    private javax.swing.JTextField jEnroll;
    private javax.swing.JTextField jFatherN;
    private javax.swing.JTextField jFirstN;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLastN;
    private javax.swing.JTextField jMob;
    private javax.swing.JButton jRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
