/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.student.attendance;

import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abc
 */
public class TotalStudentData extends javax.swing.JPanel {
    int tot = 0, cur = 0;
static int ssem=0;
static String en;
   DefaultTableModel model;

   
    public TotalStudentData(int sem) {
        initComponents();
                ssem=sem;


    
            s = new StudentBean();
        int num = s.getTotal(sem);
       if (num >= 1) {
            cur = 1;
            tot = num;
         //   s = s.getRecord(1);
            //show(e);
        }
                int i=1;
for(i=1;i<=tot;i++){
 Vector q=new Vector();
s.getRecord(i,ssem);

en=s.getsenrollno();
q.addElement(s.getsenrollno());
q.addElement(s.getSfirstname());
q.addElement(s.getSlastname());
q.addElement(s.getSfname());
q.addElement(s.getSbranch());
q.addElement(s.getSsem());
q.addElement(s.getSmobile());
q.addElement(s.getSemail());




ab.getRecord(en);
q.addElement(ab.getAttotal());
q.addElement(ab.getAtattended());
q.addElement(ab.getAtpercentage());
q.addElement(ab.getAptotal());
q.addElement(ab.getApattended());
q.addElement(ab.getAppercentage());
q.addElement(ab.getAspecial());
q.addElement(ab.getAfinal());


Vector rows = new Vector();

              rows.addElement(q);
           DefaultTableModel model=(DefaultTableModel) jTable1.getModel();

        model.addRow(q);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enroll No.", "First Name", "Last Name", "Father Name", "Branch", "Sem", "Mobile", "E-Mail", "Total Theory", "Theory Attend", "Theory %", "Total Lab. ", "Lab. Attend", "Lab. % ", "Special Attend", "Final Atted %"
            }
        ));
        jTable1.setMinimumSize(new java.awt.Dimension(250, 0));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(5).setMinWidth(50);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(13).setMinWidth(10);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1299, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    public static void main(String[] args) {
        JFrame fr = new JFrame("Total Student Data");
        fr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //fr.setContentPane(new TotalStudentData());
        fr.setBounds(80,140, 1230,540);
        fr.setVisible(true);
    }
    
      StudentBean s=new StudentBean();
AttendanceBean1 ab=new AttendanceBean1();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
