/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.student.attendance;

import javax.swing.JFrame;

/**
 *
 * @author abc
 */
public class UpdatePanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdatePanel
     */
    public UpdatePanel() {
        initComponents();
         LoginBean lb=new LoginBean();
        lb.getRecord();
        jtf.setText(lb.getUsername());
        jpf.setText(lb.getPassword());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbu = new javax.swing.JButton();
        jl = new javax.swing.JLabel();
        jpf = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Update Form");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 174, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("UserName");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 100, 30));

        jtf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        add(jtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 100, 30));

        jbu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbu.setForeground(new java.awt.Color(0, 153, 153));
        jbu.setText("Update");
        jbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuActionPerformed(evt);
            }
        });
        add(jbu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 90, 30));

        jl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(jl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 246, 37));

        jpf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        add(jpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuActionPerformed
       LoginBean lb=new LoginBean();
        lb.setLid(1);
        lb.setUsername(jtf.getText());
        lb.setPassword(jpf.getText());
        boolean b=lb.update();
        if(b){
            jl.setText("Update successfull");
        }
 else{
           jl.setText("username or password is incorect");
 }

    }//GEN-LAST:event_jbuActionPerformed


    
    
       public static void main(String[] args) {
        JFrame fr = new JFrame("Update Profile");
        fr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fr.setContentPane(new UpdatePanel());
        fr.setBounds(500, 100, 500,375);
        fr.setVisible(true);
    }
    LoginBean lb = new LoginBean();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbu;
    private javax.swing.JLabel jl;
    private javax.swing.JTextField jpf;
    private javax.swing.JTextField jtf;
    // End of variables declaration//GEN-END:variables
}
